### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/share/mime/packages/freedesktop.org.xml

### ISSUE THREAD

**Issue by sanak** [gtt-project/docker-gtt#28]
**Problem**
When executing `docker-compose up -d` after removing gtt (redmine) docker container/image, the following error happen.
```
gtt_1            | rake aborted!
gtt_1            | Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/share/mime/packages/freedesktop.org.xml
gtt_1            | /usr/local/bundle/gems/mimemagic-0.3.10/lib/mimemagic/tables.rb:69:in `initialize'
gtt_1            | /usr/local/bundle/gems/mimemagic-0.3.10/lib/mimemagic/tables.rb:69:in `open'
gtt_1            | /usr/local/bundle/gems/mimemagic-0.3.10/lib/mimemagic/tables.rb:69:in `open_mime_database'
gtt_1            | /usr/local/bundle/gems/mimemagic-0.3.10/lib/mimemagic/tables.rb:73:in `parse_database'
gtt_1            | /usr/local/bundle/gems/mimemagic-0.3.10/lib/mimemagic.rb:8:in `<top (required)>'
gtt_1            | /usr/src/redmine/config/application.rb:18:in `<top (required)>'
gtt_1            | /usr/src/redmine/Rakefile:5:in `<top (required)>'
gtt_1            | /usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
gtt_1            | (See full trace by running task with --trace)
```

**To Reproduce**
Execute `docker-compose up -d`.

**Expectation**
gtt container (service) should start without error.

**Links**
This error cause is recent Rails mimemagic license issue (https://qiita.com/Esfahan/items/45c0cdeb29509b7ec1c5), and it should be solved after upgrading Redmine 4.2.0 which switch to use mimemagic => marcel, but RedMica latest (1.2.1) version seems not to include the patch, so I will apply the same patch in `patches` folder after upgrading RedMica 1.2.1.
- https://www.redmine.org/issues/34969
- https://github.com/redmica/redmica/blob/v1.2.1/doc/CHANGELOG.md#redmica-121---2021-03-21

**Comment by sanak** [comment]
Hmm... RedMica 1.2.1 + patching way seems to be a bit difficult, so I will keep current RedMica version and install mimemagic dependency (`freedesktop.org.xml`).
